name: Validation
on: [pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Config
        run: |
          npm i
      - name: Run lint and unit tests
        run: |
          npm test
          npm run lint
